// Mock database — replace with real API responses once the Express backend exists.
// Lifestyle values are the vocabulary compatibility.js and the filters compare against.

// Bump this whenever seedListings changes. ListingsContext compares it against
// what's saved in localStorage and resets to the fresh seed set on mismatch —
// otherwise browsers with old cached data would never see updated seed listings,
// since localStorage always wins over the in-code defaults once it's populated.
export const SEED_VERSION = "2";

export const seedUser = {
  id: "me",
  name: "You",
  email: "",
  avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80",
  role: "tenant",
  age: null,
  gender: null,
  occupation: null,
  description: "",
  profileComplete: false,
  lifestyle: {
    cleanliness: "neat",
    sleepSchedule: "early",
    socialLevel: "quiet",
    smoking: false,
    pets: "friendly",
  },
  budget: { min: 400000, max: 700000 },
};

// 15 listings spanning five Nigerian cities and a mix of property types —
// apartments, studios, duplexes, and private rooms — each with its own
// specs (bedrooms/bathrooms/size/amenities) for the listing detail page.
export const seedListings = [
  {
    id: "lekki-2bed",
    title: "Spacious 2-Bedroom Serviced Apartment with 24/7 Power",
    location: "Lekki Phase 1, Lagos",
    city: "Lagos",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    price: 1800000,
    rating: 4.9,
    verified: true,
    propertyType: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    furnished: true,
    sizeSqm: 110,
    availableFrom: "2026-10-01",
    leaseTerm: "12 months",
    amenities: ["24/7 Power", "Serviced", "Fibre Internet", "Gated Security", "Borehole Water", "Parking"],
    tags: ["24/7 Power", "Furnished", "Serviced"],
    posterName: "Adeola O.",
    posterAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&q=80",
    description:
      "Tucked inside a quiet, gated street off Admiralty Way, this contemporary two-bedroom sanctuary offers dual industrial generators, solar-inverter backup, and an on-site water treatment plant.",
  },
  {
    id: "yaba-shared",
    title: "Roommate Needed for 2-Bedroom Flat",
    location: "Yaba, Lagos",
    city: "Lagos",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
    price: 200000,
    verified: false,
    propertyType: "Apartment",
    bedrooms: 2,
    bathrooms: 1,
    furnished: false,
    sizeSqm: 75,
    availableFrom: "2026-09-15",
    leaseTerm: "12 months",
    amenities: ["Shared Kitchen", "Prepaid Meter", "Close to Bus Stop"],
    tags: ["M/F", "Working Prof.", "Bills Included"],
    posterName: "Michael B.",
    posterAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    description: "Looking for a working professional to share a 2-bedroom flat near Sabo. Bills split evenly, quiet street.",
  },
  {
    id: "ikeja-studio",
    title: "Cozy Studio Apartment",
    location: "Ikeja GRA, Lagos",
    city: "Lagos",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    price: 850000,
    rating: 5.0,
    verified: true,
    propertyType: "Studio",
    bedrooms: 0,
    bathrooms: 1,
    furnished: true,
    sizeSqm: 45,
    availableFrom: "2026-09-01",
    leaseTerm: "12 months",
    amenities: ["Generator", "24-Hour Security", "Fitted Kitchenette"],
    tags: ["Entire Place", "Generator", "Security"],
    posterName: "Property Co.",
    posterAvatar: null,
    description: "A fully self-contained studio with dedicated generator backup and 24-hour gated security.",
  },
  {
    id: "ikoyi-luxury",
    title: "Luxury 3-Bedroom Duplex with Pool Access",
    location: "Old Ikoyi, Lagos",
    city: "Lagos",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80",
    price: 4500000,
    rating: 4.8,
    verified: true,
    propertyType: "Duplex",
    bedrooms: 3,
    bathrooms: 4,
    furnished: true,
    sizeSqm: 240,
    availableFrom: "2026-11-01",
    leaseTerm: "12 months",
    amenities: ["Swimming Pool", "Gym", "24/7 Power", "2 Parking Spaces", "Estate Security"],
    tags: ["Entire Place", "Pool", "Gym", "24/7 Power"],
    posterName: "Ikoyi Prime Estates",
    posterAvatar: null,
    description:
      "An executive 3-bedroom duplex in a serviced compound with shared pool and gym access, dedicated parking for two cars, and full-time estate security.",
  },
  {
    id: "vi-shared-flat",
    title: "Roommate Wanted — Executive 2-Bed in VI",
    location: "Victoria Island, Lagos",
    city: "Lagos",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    price: 550000,
    rating: 4.6,
    verified: true,
    propertyType: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    furnished: true,
    sizeSqm: 95,
    availableFrom: "2026-09-20",
    leaseTerm: "12 months",
    amenities: ["Weekly Cleaning", "Fibre Internet", "Furnished", "Close to Work Hubs"],
    tags: ["M/F", "Working Prof.", "Furnished"],
    posterName: "Chiamaka O.",
    posterAvatar: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=200&q=80",
    description:
      "Looking for a tidy, professional roommate to share a bright 2-bedroom apartment two streets from Tiamiyu Savage. Cleaner comes weekly, bills split 50/50.",
  },
  {
    id: "surulere-room",
    title: "Furnished Room in Family Compound",
    location: "Surulere, Lagos",
    city: "Lagos",
    image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80",
    price: 150000,
    verified: false,
    propertyType: "Room",
    bedrooms: 1,
    bathrooms: 1,
    furnished: true,
    sizeSqm: 20,
    availableFrom: "2026-09-05",
    leaseTerm: "6 months",
    amenities: ["Shared Kitchen"],
    tags: ["Furnished", "Shared Kitchen"],
    posterName: "Ngozi A.",
    posterAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&q=80",
    description:
      "Pay the caretaker directly by Western Union before viewing to hold the room — moving fast, no inspection needed.",
  },
  {
    id: "ajah-affordable",
    title: "Affordable Self-Contained Studio",
    location: "Ajah, Lagos",
    city: "Lagos",
    image: "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800&q=80",
    price: 280000,
    verified: true,
    propertyType: "Self-Contained",
    bedrooms: 1,
    bathrooms: 1,
    furnished: false,
    sizeSqm: 35,
    availableFrom: "2026-09-10",
    leaseTerm: "12 months",
    amenities: ["Newly Built", "Prepaid Meter", "Borehole Water", "Tiled Floors"],
    tags: ["Entire Place", "Newly Built"],
    posterName: "Femi Properties",
    posterAvatar: null,
    description:
      "Brand new self-contained studio in a quiet Ajah estate, walking distance to the expressway. Prepaid meter, borehole water, tiled throughout.",
  },
  {
    id: "magodo-family-room",
    title: "Private Room in Gated Magodo Estate",
    location: "Magodo GRA, Lagos",
    city: "Lagos",
    image: "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&q=80",
    price: 420000,
    rating: 4.7,
    verified: true,
    propertyType: "Room",
    bedrooms: 1,
    bathrooms: 1,
    furnished: false,
    sizeSqm: 25,
    availableFrom: "2026-10-15",
    leaseTerm: "12 months",
    amenities: ["Gated Estate", "Generator", "Shared Living Room", "24-Hour Security"],
    tags: ["Private Room", "Security", "Generator"],
    posterName: "Tolu B.",
    posterAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=80",
    description:
      "Quiet private room in a family home inside a fully gated Magodo estate. Shared living room and kitchen, generator backup during outages, 24-hour security gate.",
  },
  {
    id: "ikorodu-budget",
    title: "Budget Room for Students & Young Professionals",
    location: "Ikorodu, Lagos",
    city: "Lagos",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
    price: 90000,
    verified: false,
    propertyType: "Room",
    bedrooms: 1,
    bathrooms: 1,
    furnished: false,
    sizeSqm: 18,
    availableFrom: "2026-09-01",
    leaseTerm: "6 months",
    amenities: ["Shared Kitchen", "Shared Bathroom", "Close to Garage"],
    tags: ["Shared Kitchen", "Budget Friendly"],
    posterName: "Emeka N.",
    posterAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    description: "No agent fees, move in this week. Shared kitchen and bathroom with two other tenants, walking distance to Ikorodu garage.",
  },
  {
    id: "wuse-abuja-3bed",
    title: "Modern 3-Bedroom Apartment in Wuse 2",
    location: "Wuse 2, Abuja",
    city: "Abuja",
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80",
    price: 3200000,
    rating: 4.7,
    verified: true,
    propertyType: "Apartment",
    bedrooms: 3,
    bathrooms: 3,
    furnished: true,
    sizeSqm: 180,
    availableFrom: "2026-10-01",
    leaseTerm: "12 months",
    amenities: ["24/7 Power", "Elevator", "Gym", "Gated Security", "Parking"],
    tags: ["Entire Place", "Furnished", "24/7 Power"],
    posterName: "Capital Homes Abuja",
    posterAvatar: null,
    description:
      "A bright, modern 3-bedroom apartment in the heart of Wuse 2, close to embassies and the central business district. Building has an elevator, gym, and round-the-clock security.",
  },
  {
    id: "gwarinpa-abuja-room",
    title: "Room in 2-Bedroom Bungalow, Gwarinpa",
    location: "Gwarinpa, Abuja",
    city: "Abuja",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
    price: 380000,
    verified: false,
    propertyType: "Room",
    bedrooms: 1,
    bathrooms: 1,
    furnished: false,
    sizeSqm: 22,
    availableFrom: "2026-09-25",
    leaseTerm: "12 months",
    amenities: ["Shared Compound", "Borehole Water", "Quiet Neighborhood"],
    tags: ["M/F", "Bills Included"],
    posterName: "Grace O.",
    posterAvatar: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=200&q=80",
    description:
      "Sharing a bungalow in a quiet Gwarinpa estate with one other tenant. Great for someone who works remotely and wants a calm environment.",
  },
  {
    id: "maitama-abuja-luxury",
    title: "Fully Serviced 1-Bedroom Apartment",
    location: "Maitama, Abuja",
    city: "Abuja",
    image: "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800&q=80",
    price: 5000000,
    rating: 4.9,
    verified: true,
    propertyType: "Apartment",
    bedrooms: 1,
    bathrooms: 1,
    furnished: true,
    sizeSqm: 85,
    availableFrom: "2026-11-15",
    leaseTerm: "12 months",
    amenities: ["Concierge", "Housekeeping", "24/7 Power", "Fibre Internet", "Swimming Pool"],
    tags: ["Entire Place", "Serviced", "24/7 Power"],
    posterName: "Maitama Executive Suites",
    posterAvatar: null,
    description:
      "A fully serviced diplomatic-zone apartment aimed at executives and corporate lets — housekeeping three times a week, concierge desk, and pool access.",
  },
  {
    id: "ph-gra-2bed",
    title: "2-Bedroom Flat in GRA Phase 2",
    location: "GRA Phase 2, Port Harcourt",
    city: "Port Harcourt",
    image: "https://images.unsplash.com/photo-1560185008-b033106af5c3?w=800&q=80",
    price: 1100000,
    rating: 4.5,
    verified: true,
    propertyType: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    furnished: false,
    sizeSqm: 100,
    availableFrom: "2026-09-30",
    leaseTerm: "12 months",
    amenities: ["Generator", "Gated Estate", "Parking", "Water Treatment Plant"],
    tags: ["Entire Place", "Generator", "Security"],
    posterName: "Chidi Realtors PH",
    posterAvatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=200&q=80",
    description:
      "Spacious unfurnished 2-bedroom flat in one of Port Harcourt's most sought-after GRA streets. Close to shopping malls and international schools.",
  },
  {
    id: "ibadan-bodija-studio",
    title: "Self-Contained Studio Near Bodija Market",
    location: "Bodija, Ibadan",
    city: "Ibadan",
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80",
    price: 250000,
    verified: false,
    propertyType: "Self-Contained",
    bedrooms: 1,
    bathrooms: 1,
    furnished: false,
    sizeSqm: 30,
    availableFrom: "2026-09-05",
    leaseTerm: "12 months",
    amenities: ["Prepaid Meter", "Close to Market", "Tarred Road Access"],
    tags: ["Entire Place", "Budget Friendly"],
    posterName: "Bunmi A.",
    posterAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    description: "Newly renovated self-contained studio a five-minute walk from Bodija Market. Great for students at UI or young professionals.",
  },
  {
    id: "enugu-independence-3bed",
    title: "Room Share in 3-Bedroom Duplex, Independence Layout",
    location: "Independence Layout, Enugu",
    city: "Enugu",
    image: "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&q=80",
    price: 300000,
    rating: 4.4,
    verified: true,
    propertyType: "Duplex",
    bedrooms: 1,
    bathrooms: 1,
    furnished: true,
    sizeSqm: 28,
    availableFrom: "2026-10-10",
    leaseTerm: "12 months",
    amenities: ["Furnished Room", "Shared Living Room", "Generator", "Quiet Street"],
    tags: ["M/F", "Furnished"],
    posterName: "Obinna K.",
    posterAvatar: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=200&q=80",
    description:
      "Sharing a 3-bedroom duplex in the leafy Independence Layout with one other tenant. Furnished room, shared living space, generator backup.",
  },
];

export const seedRoommates = [
  {
    id: "sarah-j",
    name: "Sarah J.",
    age: 26,
    role: "Graphic Designer",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80",
    location: "Looking in Yaba, Surulere",
    verified: true,
    bio: "Graphic designer looking for a quiet, clean space. I love houseplants and occasional weekend baking.",
    description:
      "I've been freelancing for design agencies for about three years and mostly work from home, so I really value a calm, uncluttered living space during the day. In the evenings I unwind with a book or a baking project — nothing too loud. I'm ideally looking for one or two roommates who keep shared spaces tidy and don't mind quiet weekdays. Happy to split grocery runs and the occasional home-cooked dinner.",
    lifestyle: { cleanliness: "neat", sleepSchedule: "night_owl", socialLevel: "quiet", smoking: false, pets: "friendly" },
    budget: { min: 400000, max: 700000 },
  },
  {
    id: "david-balogun",
    name: "David Balogun",
    age: 26,
    role: "Lead Product Designer at FinTech Co.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80",
    location: "Looking in Lekki Phase 1, VI & Yaba",
    verified: true,
    bio: "Product designer and creative technologist working remotely. I keep common areas uncluttered and calm.",
    description:
      "I work hybrid — usually three days from home — so a reliable internet connection and a quiet daytime environment matter a lot to me. I'm an early riser, love making pour-over coffee before calls, and cook proper meals most evenings (my jollof has a bit of a reputation). I'm easygoing about most things but do care about a clean kitchen and everyone pulling their weight on shared bills. Looking for someone respectful and communicative to split a 2-bedroom place with.",
    lifestyle: { cleanliness: "neat", sleepSchedule: "early", socialLevel: "moderate", smoking: false, pets: "friendly" },
    budget: { min: 500000, max: 800000 },
  },
  {
    id: "elena-r",
    name: "Elena R.",
    age: 28,
    role: "Tech, Product Manager",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80",
    location: "Looking in Ikeja, Magodo",
    verified: true,
    bio: "Social butterfly, working in tech. I enjoy hosting occasional dinner parties and trying new recipes.",
    description:
      "I'm a product manager at a growing startup, which means my schedule is unpredictable but usually daytime-heavy. On weekends I love having friends over for dinner — nothing wild, just good food and conversation — so I'm hoping for a roommate who's fine with occasional guests and doesn't mind a lively household every so often. I'm generally tidy but not obsessive about it, and I'm flexible on most lifestyle things as long as we communicate openly.",
    lifestyle: { cleanliness: "average", sleepSchedule: "early", socialLevel: "social", smoking: false, pets: "neutral" },
    budget: { min: 350000, max: 600000 },
  },
  {
    id: "michael-b",
    name: "Michael B.",
    age: 30,
    role: "Grad Student",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
    location: "Looking in Yaba",
    verified: false,
    bio: "Grad student spending most time on campus. Very laid back but appreciate common areas kept tidy.",
    description:
      "I'm finishing up a master's program at UNILAG, so I'm out of the house most of the day attending lectures or studying at the library. I'm genuinely low-maintenance as a roommate — I don't host often, I'm quiet, and I just want a clean, calm place to come back to. Budget is tight since I'm a student, so I'm hoping to find someone equally practical to split costs with.",
    lifestyle: { cleanliness: "average", sleepSchedule: "early", socialLevel: "quiet", smoking: false, pets: "no" },
    budget: { min: 150000, max: 300000 },
  },
];
